remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
title: "Aritro Shome's Blog"
author: "Aritro Shome"
description: "A personal experience of college and technology, with personal life"

